# services:
#   dev:
#     build:
#       context: .
#       target: dev
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./:/app
#       - /app/node_modules

#   prod:
#     build:
#       context: .
#       target: prod
#     ports:
#       - "80:80" # Maps host port 80 → container port 80 (NGINX)
