services:       # Defines the containers to run
  dev:          # Service name (development)
    build:
      context: .       # Build from current directory
      target: dev      # Use the "dev" stage from Dockerfile
    ports:
      - "5173:5173"    # Maps host port 5173 → container port 5173 (Vite dev server)
    volumes:
      - ./:/app        # Sync local files with container (live reload)
      - /app/node_modules  # Preserve node_modules (avails host conflicts)
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true

  prod:         # Service name (production)
    build:
      context: .
      target: prod     # Use the "prod" stage from Dockerfile
    ports:
      - "80:80"        # Maps host port 80 → container port 80 (NGINX)