name: Smoke Test
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run dev -- --host &
      - run: sleep 10 && curl -f http://localhost:5173